### ISSUE TITLE
Are you aware of GopherJS?

### ISSUE THREAD

**Issue by dmitshur** [tredoe/go2js#8]
From README,

> ## Status
> 
> Inactive | Incomplete
> 
> Sorry to not be able to continue with this project for some time, but I have to
> work very hard in third projects.
> 
> Although I follow being interested in be able to use Go in the browser.

Since you say you're interested in being able to use Go in the browser, I wanted to ask...

I wanted to ask, are you aware of GopherJS project? It has gotten pretty far, including support for goroutines, channels, and select recently.

[https://github.com/gopherjs/gopherjs](https://github.com/gopherjs/gopherjs#gopherjs---a-compiler-from-go-to-javascript)
https://groups.google.com/forum/#!forum/gopherjs

**Comment by peppapiggie** [comment]
gopherjs is trying to support both node.js and browser and as a result not usable anywhere at all. The code it produces is way too bloated and inefficient. Goroutines and channels is not something that important on the client to pay that price. Although go2js is deprecated I still prefer it over gopherjs and actively using it. It may have its limitations, but the produced JS is predictable and simple. Maybe, it's even worth to fork the project and continue its development.

**Comment by shurcooL** [comment]
@peppapiggie, thanks for feedback on GopherJS. Let me address your points.

> gopherjs is trying to support both node.js and browser and as a result not usable anywhere at all. The code it produces is way too bloated and inefficient.

The main goal of GopherJS is to support the entire Go language specification. That includes goroutunes, channels, select statements, as well as the type system, defer, byte and rune slices, etc. A program compiled with it should have identical results (as long as supported packages are used). That's the main reason GopherJS output is complicated is because of that. Node.js support is not the reason for any complexity.

> Goroutines and channels is not something that important on the client to pay that price.

This is a matter of preference. For some, it's a critical feature because it lets one write/use Go code that works anywhere, without having to artificially limit the language features you use.

> Although go2js is deprecated I still prefer it over gopherjs and actively using it. It may have its limitations, but the produced JS is predictable and simple.

I think that's fair, it sounds like there are 2 valid and distinct approaches. One is that GopherJS takes, to support all Go language features at any cost (but try to improve performance as much as possible). The other approach that go2js takes is to have a language with Go-like syntax and a subset of Go features that maps very directly to JavaScript.

Hope that helps explain the difference. I don't want you to think that Node.js is the primary cause of what you're seeing.
